"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.String(length=32), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_independent_educator', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('learner_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('error_type', sa.String(length=48), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('recent_per_100_tokens', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_progress_user_id'), 'learner_progress', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_language'), 'submissions', ['language'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('correction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('corrected', sa.Text(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_runs_submission_id'), 'correction_runs', ['submission_id'], unique=False)
    op.create_table('edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('op', sa.String(length=8), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('error_type', sa.String(length=48), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=96), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_calibrated', sa.Boolean(), nullable=False),
    sa.Column('gate_status', sa.String(length=16), nullable=False),
    sa.Column('gate_reason', sa.Text(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('learner_decision', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['correction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edits_run_id'), 'edits', ['run_id'], unique=False)
    op.create_table('adjudications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edit_id', sa.Integer(), nullable=False),
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('revised_replacement', sa.Text(), nullable=True),
    sa.Column('error_type_override', sa.String(length=48), nullable=True),
    sa.Column('meaning_changed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reviewer_independent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edit_id'], ['edits.id'], ),
    sa.ForeignKeyConstraint(['educator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjudications_edit_id'), 'adjudications', ['edit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjudications_edit_id'), table_name='adjudications')
    op.drop_table('adjudications')
    op.drop_index(op.f('ix_edits_run_id'), table_name='edits')
    op.drop_table('edits')
    op.drop_index(op.f('ix_correction_runs_submission_id'), table_name='correction_runs')
    op.drop_table('correction_runs')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_language'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_learner_progress_user_id'), table_name='learner_progress')
    op.drop_table('learner_progress')
    op.drop_table('users')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
